---
- name: install nfs services
  apt:
    name: "{{ item }}"
  with_items:
    - rpcbind
    - nfs-common

- name: start nfs services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - rpcbind
